global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'capturador_network'
    static_configs:
      - targets: ['host.docker.internal:8000'] # Apunta al puerto expuesto por el script de captura

